### ISSUE TITLE
ProcessorLog deprecated

### ISSUE THREAD

**Issue by sheilacheng** [pcgrenier/nifi-examples#1]
I tried your example and everything works great except that ProcessorLog is no longer. I substitute with ComponentLog and things are fine.

**Comment by pcgrenier** [comment]
Thanks for pointing this out. I had fixed it in the [sample-processors branch ](https://github.com/pcgrenier/nifi-examples/tree/sample-processor/sample-processor/src/main/java/rocks/nifi/examples/processors) but not duplicated in to the master branch.

**Comment by sheilacheng** [comment]
I'm just learning Nifi so I appreciate your example. Thanks.

**Comment by pcgrenier** [comment]
No problem, we are always looking for topics to write about on [nifi.rocks](http://nifi.rocks). So please if you have any questions just ask.
